// Renders the Vibespan mark at a range of sizes so the geometry can be eyeballed, and proves
// Geometry.Parse accepts the path at runtime - compiling only proves the string is a string,
// and this path is generated by tools/trace-mark.py rather than hand-written.
using System;
using System.IO;
using System.Windows.Media;
using Vibespan;

public static class TestGlyph
{
    [STAThread]
    public static void Main()
    {
        var brush = new SolidColorBrush(Color.FromRgb(0xDA, 0x77, 0x56));
        brush.Freeze();

        if (Brand.Starburst == null || Brand.Starburst.IsEmpty())
        {
            Console.WriteLine("FAIL: Brand.Starburst parsed to an empty geometry");
            Environment.Exit(1);
        }

        foreach (int px in new[] { 256, 64, 16 })
        {
            byte[] png = Gauge.GlyphPng(px, brush, Brand.Starburst);
            string outPath = Path.Combine("docs", "glyph-" + px + ".png");
            File.WriteAllBytes(outPath, png);
            Console.WriteLine("wrote " + outPath + "  (" + png.Length + " bytes)");
        }
        Console.WriteLine("Geometry.Parse accepted the traced path at runtime.");
    }
}
