// The Vibespan mark, as vector geometry.
//
// GENERATED by tools/trace-mark.py from VS-Logo-A.png - do not hand-edit.
//
// Traced rather than eyeballed: the outline is extracted from the artwork, simplified with
// Ramer-Douglas-Peucker, and checked back against the source raster at 0.9824 IoU (1.76% of
// pixels differ). The generator refuses to write below 0.97, so drift is caught rather than
// argued about.
//
// Vector and not a bitmap because the tray icon is TINTED at run time - it takes the colour
// of the worst current usage level - so a fixed-colour PNG could not do the job, and this
// also stays sharp at any DPI.
//
// Coordinates run 0..100 on both axes with the mark centred, so Stretch.Uniform fills
// whatever box it is given.
using System.Windows.Media;

namespace Vibespan
{
    public static class Brand
    {
        const string StarburstPath =
            "M59.33,0L60.67,0.12L62.01,0.85L62.87,1.83L63.35,3.29L63.35,33.29L63.6,33.54L65.3,33.41L65.55,33."
            + "17L65.67,32.07L68.6,31.95L68.72,27.8L74.45,27.8L74.57,33.41L78.48,33.41L78.72,30.73L83.23,30.85L"
            + "83.23,35.49L79.57,35.61L78.48,35.37L77.87,35.73L77.87,40.24L80.67,40.49L80.67,43.66L77.87,43.78L"
            + "77.87,42.56L77.62,42.32L73.96,42.32L73.72,42.56L73.72,46.71L77.87,46.95L77.87,52.2L81.28,52.32L8"
            + "1.52,52.56L81.52,56.34L81.28,56.59L77.62,56.59L77.38,55L74.7,55L74.45,55.24L74.45,57.8L77.38,57."
            + "93L77.5,60.24L71.52,60.24L71.16,60.49L71.16,64.39L71.4,64.63L72.26,64.63L72.26,69.02L69.09,69.02"
            + "L68.84,67.68L64.7,67.8L64.7,72.68L64.94,72.93L66.77,73.05L66.77,77.56L63.35,77.8L63.35,96.71L62."
            + "62,98.54L61.4,99.63L60.3,100L59.09,100L57.38,99.27L56.65,98.41L56.04,96.83L56.04,66.95L55.79,66."
            + "71L55.43,66.71L54.82,67.44L43.48,87.93L42.13,88.9L39.82,89.15L38.48,88.54L37.13,86.71L37.01,84.8"
            + "8L37.26,84.15L49.09,63.05L49.33,62.56L49.09,61.95L48.72,61.83L47.26,62.68L23.72,77.56L21.4,77.56"
            + "L20.18,76.83L19.21,75.49L18.96,74.63L19.09,73.17L19.7,71.83L20.67,70.85L44.33,55.98L45.18,55.24L"
            + "45.18,54.76L44.82,54.39L19.7,54.39L18.11,53.66L17.26,52.68L16.77,51.59L16.77,49.88L17.38,48.54L1"
            + "8.6,47.44L20.06,46.95L44.94,46.95L45.3,46.59L44.82,45.73L20.18,30.73L18.84,29.02L18.6,28.05L18.7"
            + "2,26.59L19.21,25.61L20.79,24.27L21.65,24.02L23.6,24.27L48.11,39.27L49.09,39.51L49.33,39.27L49.09"
            + ",38.29L38.23,19.15L37.99,18.29L38.11,16.59L38.84,15.24L40.43,14.15L42.26,14.02L43.72,14.63L44.7,"
            + "15.61L54.57,33.17L55.06,33.66L55.67,33.66L56.04,33.29L56.04,3.17L56.52,1.83L57.5,0.73L59.33,0ZM7"
            + "0.06,34.76L72.74,34.76L72.74,37.44L70.06,37.44L70.06,34.76Z";

        /// <summary>The starburst, frozen once. Fill it with whatever brush the caller wants.</summary>
        public static readonly Geometry Starburst = Build();

        static Geometry Build()
        {
            Geometry g = Geometry.Parse(StarburstPath);
            g.Freeze();
            return g;
        }
    }
}
